// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token     string `json:"token"`
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	ExpiresAt int64  `json:"expires_at"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
}

type RegisterResp struct {
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

type VerifyTokenReq struct {
	Token string `json:"token"`
}

type VerifyTokenResp struct {
	Valid    bool   `json:"valid"`
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
}
