apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  platform.yaml: |
    Name: {{ .Values.config.name | quote }}
    Host: {{ .Values.config.host | quote }}
    Port: {{ .Values.config.port }}
    Timeout: {{ .Values.config.timeout }}
    MySQL:
      DataSource: {{ .Values.config.mysql.datasource | quote }}
    GitHub:
      Token: ""
      Org: {{ .Values.config.github.org | quote }}
