# 镜像配置
image:
  repository: ghcr.io/mirai-zen/forge-platform
  tag: latest
  #pullPolicy: IfNotPresent
  # 总是拉取最新的镜像
  pullPolicy: Always


# Service
service:
  type: ClusterIP
  port: 8880

# 资源配额
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

# 业务启动配置（所有环境公共默认值，环境特定值在 values-{env}.yaml 覆盖）
