apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mirai-zen/forge
    targetRevision: main
    path: deploy/charts/platform
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: forge-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
